//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardPaying
    {
        public int CardPayingId { get; set; }
        public string CardName { get; set; }
        public string CardNumber { get; set; }
        public Nullable<System.DateTime> TimeOfPayment { get; set; }
    }
}
