//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNew
    {
        public int UserNewId { get; set; }
        public string UserNewName { get; set; }
        public Nullable<int> UserNewBalance { get; set; }
        public string UserNewPassword { get; set; }
    }
}
